helm_chart( dependencies=[":postgres"])

helm_artifact(
    name="postgres", artifact="postgresql", description="a postgres external chart", version="14.3.1", repository="https://charts.bitnami.com/bitnami"
)
